
all:
	g++ -o test test.cpp -L.. -lcam -I/usr/local/include/opencv -L/usr/local/lib -lcv -lcxcore -lcvaux -lhighgui
	g++ -o two two.cpp -L.. -lcam -I/usr/local/include/opencv -L/usr/local/lib -lcv -lcxcore -lcvaux -lhighgui

clean:
	rm -f test
	rm -f two



